before:
  hooks:
    - go mod tidy

builds:
  - binary: logfmt
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0

archives:
  - format_overrides:
      - goos: windows
        formats: ["zip"]

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
